### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by MissXy** [okbalefthanded/bci_toolbox#5] opened 2018-08-07 11:16 UTC
I would like to ask you how to run a file, for example, I have downloaded the data set, how to run dataio_create_epochs_SM_SanDiego. m

**Comment by okbalefthanded** [comment] 2018-08-07 15:42
The dataio_create_epochs, needs to be run separately to create data, first make sure to have the San Diego dataset in the dataset folder, then you need to specify the epoch_length (window length) of signal and frequency bands to filter the signal.
before running the next line, run setup script (to add the toolbox to your MATLAB's path) 

epoch_length = [0 4000];
filter_band = [5 40];
dataio_create_epochs_SM_SanDiego(epoch_length, filter_band)

**Comment by MissXy** [comment] 2018-08-09 01:57
thank you very much. I am a novice, your reply has been of great help to me. It would be appreciated if you could give an example in Readme.md;

**Comment by okbalefthanded** [comment] 2018-08-09 22:48
@MissXy you're welcome, I'll add more demos and detailed documentation progressively, please confirm if the issue is solved so I can closed it.

**Comment by MissXy** [comment] 2018-08-10 00:47
My problem has been solved. 
1. There is, however, one small problem. Line 32 of file dataio_create_epochs_SM_SanDiego. m:
`disp('Creating epochs for Tsinghua lab JPFM SSVEP dataset');`
I suggest:
`disp('Creating epochs for SanDiego lab JPFM SSVEP dataset');`
2. There was an error when I ran file define_approach_SSVEP.m. , The path error.
Line 43 of file  dataio_read_SSVEP_Single.m:`ssvep_sandiego = [path 'ssvep_sandiego\SM\' subj];`
So Line 34 of file dataio_create_epochs_SM_SanDiego. m:
`set_path = 'datasets\sandiego_ssvep';`
I suggest:
`set_path = 'datasets\ssvep_sandiego';`

**Comment by okbalefthanded** [comment] 2018-08-11 12:31
Thanks for the bug reminder, I had corrected it in a different local modifications that wasn't pushed. 
Fixed in dev branch

**Closed as completed** 2018-08-29 19:06 UTC

**Comment by kazila1** [comment] 2019-04-18 07:28
Hello, I ran your program with this error
Index beyond matrix dimension.
error  dataio_create_epochs_SM_SanDiego (line 77)
    subject_path = [set_path '\' dataSetFiles{subj}];
Is the path wrong? thanks

**Comment by okbalefthanded** [comment] 2019-04-18 13:07
@kazila1 please open a new issue.

**Comment by gdddara** [comment] 2019-05-18 11:57
hellio i have the same problem is that
Index beyond matrix dimension
utils_fetch_Set_Folder (line 37)
        set_path = [set_path,'SM\',dataSetFiles{end}];
and i don't know what to do

**Comment by okbalefthanded** [comment] 2019-05-18 21:13
@gdddara please open a new issue.
